### PR TITLE
Allow users to have differing word boundaries patterns

### PR DESCRIPTION
**Pull request by stuartskelton**

### CODE REVIEW

**Comment by knownasilya** [comment]
Nice, could you also add some documentation to the README for the new options? Thanks!

**Comment by stuartskelton** [comment]
I have updated the docs.

**Comment by knownasilya** [comment]
Excellent, will look to publish asap.

**Comment by stuartskelton** [comment]
cheers

**Comment by stuartskelton** [comment]
Any chance of getting a release out? as I have come to a point of needing the differing word boundaries, Thanks

**Pull request merged**
